### ISSUE TITLE
System.in does not pause

### ISSUE THREAD

**Issue by nlwillia** [spring-guides/gs-integration#11]
I found when following this guide that `System.in.read()` in Application.java did not pause as expected when using `gradlew bootRun`.  (It did work with the standalone jar.)  Apparently, this is due to a default override in Gradle.

https://discuss.gradle.org/t/why-doesnt-system-in-read-block-when-im-using-gradle/3308
http://stackoverflow.com/questions/13172137/console-application-with-java-and-gradle

The workaround is to add the following to the build script.
````
bootRun {
  standardInput = System.in
}
````
Little issues like this are a source of friction when getting started, so it would be good to either update the build script or add a footnote about it.

**Comment by artembilan** [comment]
Good catch!

Will be fixed soon

Thank you!
