### ISSUE TITLE
Guide asks to create wrong directory 

### ISSUE THREAD

**Issue by chaitanyathengdi** [spring-guides/gs-integration#13]
On the main page(`https://spring.io/guides/gs/integration/`), the guide asks users to create the standard `src/main/java/hello` bunch of directories, but the application actually has the directory structure `src/main/java/blog/`. This isn't my first guide, so not a problem for me. But it could be a problem for someone not familiar with things.

**Quote:**

Create the directory structure

In a project directory of your choosing, create the following subdirectory structure; for example, with mkdir -p src/main/java/hello on *nix systems:

```
└── src
    └── main
        └── java
            └── hello

```

**Comment by gregturn** [comment]
@artembilan Got time to peek at this one?

**Comment by artembilan** [comment]
Hi there!
I am on PTO today.
Will take a look tomorrow.

Thank you for heads up anyway!

**Comment by chaitanyathengdi** [comment]
Will this work?
![adocfile](https://cloud.githubusercontent.com/assets/14993220/16448188/c2cae3d8-3e0d-11e6-93ae-3e606cee266f.png)
