### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by WuRoc** [spring-guides/gs-integration#27]
@Autowired
    private SourcePollingChannelAdapter newsAdapter;
idea prompt error：
Could not autowire. No beans of 'SourcePollingChannelAdapter' type found.

**Comment by artembilan** [comment]
The bean is not declared directly in the code, so IDEA cannot determine what is the source for that `@Autowired`.
Unfortunately we cannot do anything with that from Spring perspective.
And I believe it won't be possible even from the IDEA side when you contact them.

Better to be sure that application works when you run it.

Thank you for understanding!

**Comment by WuRoc** [comment]
> bean 没有直接在代码中声明，因此 IDEA 无法确定它的来源是什么`@Autowired`。 不幸的是，从 Spring 的角度来看，我们无法对此做任何事情。 而且我相信当您与他们联系时，即使从 IDEA 方面也是不可能的。
> 
> 最好确保该应用程序在您运行时正常工作。
> 
> 谢谢你的理解！



> bean 没有直接在代码中声明，因此 IDEA 无法确定它的来源是什么`@Autowired`。 不幸的是，从 Spring 的角度来看，我们无法对此做任何事情。 而且我相信当您与他们联系时，即使从 IDEA 方面也是不可能的。
> 
> 最好确保该应用程序在您运行时正常工作。
> 
> 谢谢你的理解！

OK,Thanks!
